export interface Character {
  id: string
  firstName: string
  lastName: string
  gender: "male" | "female"
  model: string
  avatar: string
  audio: string
}

export const CHARACTERS: Character[] = [
  // CELESTIAL & WIND VOICES
  {
    id: "aoede",
    firstName: "Aoede",
    lastName: "Song",
    gender: "female",
    model: "Aoede",
    avatar: "/avatars/aoede.png",
    audio: "/audios/aoede.mp3",
  },
  {
    id: "zephyr",
    firstName: "Zephyr",
    lastName: "Breeze",
    gender: "male",
    model: "Zephyr",
    avatar: "/avatars/zephyr.png",
    audio: "/audios/zephyr.mp3",
  },
  {
    id: "puck",
    firstName: "Puck",
    lastName: "Mischief",
    gender: "male",
    model: "Puck",
    avatar: "/avatars/puck.png",
    audio: "/audios/puck.mp3",
  },
  {
    id: "charon",
    firstName: "Charon",
    lastName: "Ferryman",
    gender: "male",
    model: "Charon",
    avatar: "/avatars/charon.png",
    audio: "/audios/charon.mp3",
  },
  {
    id: "kore",
    firstName: "Kore",
    lastName: "Spring",
    gender: "female",
    model: "Kore",
    avatar: "/avatars/kore.png",
    audio: "/audios/kore.mp3",
  },
  {
    id: "fenrir",
    firstName: "Fenrir",
    lastName: "Wolf",
    gender: "male",
    model: "Fenrir",
    avatar: "/avatars/fenrir.png",
    audio: "/audios/fenrir.mp3",
  },
  {
    id: "leda",
    firstName: "Leda",
    lastName: "Swan",
    gender: "female",
    model: "Leda",
    avatar: "/avatars/leda.png",
    audio: "/audios/leda.mp3",
  },
  {
    id: "orus",
    firstName: "Orus",
    lastName: "Falcon",
    gender: "male",
    model: "Orus",
    avatar: "/avatars/orus.png",
    audio: "/audios/orus.mp3",
  },
  {
    id: "callirrhoe",
    firstName: "Callirrhoe",
    lastName: "Stream",
    gender: "female",
    model: "Callirrhoe",
    avatar: "/avatars/callirrhoe.png",
    audio: "/audios/callirrhoe.mp3",
  },
  {
    id: "autonoe",
    firstName: "Autonoe",
    lastName: "Mind",
    gender: "female",
    model: "Autonoe",
    avatar: "/avatars/autonoe.png",
    audio: "/audios/autonoe.mp3",
  },

  // TITANS, GIANTS & SHADOWS
  {
    id: "enceladus",
    firstName: "Enceladus",
    lastName: "Giant",
    gender: "male",
    model: "Enceladus",
    avatar: "/avatars/enceladus.png",
    audio: "/audios/enceladus.mp3",
  },
  {
    id: "iapetus",
    firstName: "Iapetus",
    lastName: "Titan",
    gender: "male",
    model: "Iapetus",
    avatar: "/avatars/iapetus.png",
    audio: "/audios/iapetus.mp3",
  },
  {
    id: "umbriel",
    firstName: "Umbriel",
    lastName: "Shadow",
    gender: "male",
    model: "Umbriel",
    avatar: "/avatars/umbriel.png",
    audio: "/audios/umbriel.mp3",
  },
  {
    id: "algieba",
    firstName: "Algieba",
    lastName: "Lion",
    gender: "male",
    model: "Algieba",
    avatar: "/avatars/algieba.png",
    audio: "/audios/algieba.mp3",
  },
  {
    id: "despina",
    firstName: "Despina",
    lastName: "Nymph",
    gender: "female",
    model: "Despina",
    avatar: "/avatars/despina.png",
    audio: "/audios/despina.mp3",
  },
  {
    id: "erinome",
    firstName: "Erinome",
    lastName: "Grace",
    gender: "female",
    model: "Erinome",
    avatar: "/avatars/erinome.png",
    audio: "/audios/erinome.mp3",
  },
  {
    id: "algenib",
    firstName: "Algenib",
    lastName: "Pegasus",
    gender: "male",
    model: "Algenib",
    avatar: "/avatars/algenib.png",
    audio: "/audios/algenib.mp3",
  },
  {
    id: "rasalgethi",
    firstName: "Rasalgethi",
    lastName: "Kneeler",
    gender: "male",
    model: "Rasalgethi",
    avatar: "/avatars/rasalgethi.png",
    audio: "/audios/rasalgethi.mp3",
  },
  {
    id: "laomedeia",
    firstName: "Laomedeia",
    lastName: "Ruler",
    gender: "female",
    model: "Laomedeia",
    avatar: "/avatars/laomedeia.png",
    audio: "/audios/laomedeia.mp3",
  },
  {
    id: "achernar",
    firstName: "Achernar",
    lastName: "River",
    gender: "male",
    model: "Achernar",
    avatar: "/avatars/achernar.png",
    audio: "/audios/achernar.mp3",
  },

  // BRIGHT STARS & CONSTELLATIONS
  {
    id: "alnilam",
    firstName: "Alnilam",
    lastName: "Belt",
    gender: "male",
    model: "Alnilam",
    avatar: "/avatars/alnilam.png",
    audio: "/audios/alnilam.mp3",
  },
  {
    id: "schedar",
    firstName: "Schedar",
    lastName: "Queen",
    gender: "female",
    model: "Schedar",
    avatar: "/avatars/schedar.png",
    audio: "/audios/schedar.mp3",
  },
  {
    id: "gacrux",
    firstName: "Gacrux",
    lastName: "Cross",
    gender: "male",
    model: "Gacrux",
    avatar: "/avatars/gacrux.png",
    audio: "/audios/gacrux.mp3",
  },
  {
    id: "pulcherrima",
    firstName: "Pulcherrima",
    lastName: "Beauty",
    gender: "female",
    model: "Pulcherrima",
    avatar: "/avatars/pulcherrima.png",
    audio: "/audios/pulcherrima.mp3",
  },
  {
    id: "achird",
    firstName: "Achird",
    lastName: "Star",
    gender: "male",
    model: "Achird",
    avatar: "/avatars/achird.png",
    audio: "/audios/achird.mp3",
  },
  {
    id: "zubenelgenubi",
    firstName: "Zubenel",
    lastName: "Genubi",
    gender: "male",
    model: "Zubenelgenubi",
    avatar: "/avatars/zubenelgenubi.png",
    audio: "/audios/zubenelgenubi.mp3",
  },
  {
    id: "vindemiatrix",
    firstName: "Vindemi",
    lastName: "Atrix",
    gender: "female",
    model: "Vindemiatrix",
    avatar: "/avatars/vindemiatrix.png",
    audio: "/audios/vindemiatrix.mp3",
  },
  {
    id: "sadachbia",
    firstName: "Sadach",
    lastName: "Bia",
    gender: "female",
    model: "Sadachbia",
    avatar: "/avatars/sadachbia.png",
    audio: "/audios/sadachbia.mp3",
  },
  {
    id: "sadaltager",
    firstName: "Sadal",
    lastName: "Tager",
    gender: "male",
    model: "Sadaltager",
    avatar: "/avatars/sadaltager.png",
    audio: "/audios/sadaltager.mp3",
  },
  {
    id: "sulafat",
    firstName: "Sulafat",
    lastName: "Lyra",
    gender: "female",
    model: "Sulafat",
    avatar: "/avatars/sulafat.png",
    audio: "/audios/sulafat.mp3",
  },
]

export function getCharacter(id: string): Character | undefined {
  return CHARACTERS.find((c) => c.id === id)
}
