export interface Character {
  id: string
  firstName: string
  lastName: string
  gender: "male" | "female"
  model: string
  avatar: string
  audio: string
}

export const CHARACTERS: Character[] = [
  // AUTHORITATIVE & POWERFUL
  {
    id: "robert",
    firstName: "Robert",
    lastName: "Reed",
    gender: "male",
    model: "zeus",
    avatar: "/avatars/robert.png",
    audio: "/audio/robert.mp3",
  },
  {
    id: "sophie",
    firstName: "Sophie",
    lastName: "Chen",
    gender: "female",
    model: "athena",
    avatar: "/avatars/sophie.png",
    audio: "/audio/sophie.mp3",
  },
  {
    id: "julian",
    firstName: "Julian",
    lastName: "Thorne",
    gender: "male",
    model: "jupiter",
    avatar: "/avatars/julian.png",
    audio: "/audio/julian.mp3",
  },
  {
    id: "hera",
    firstName: "Hera",
    lastName: "Volkov",
    gender: "female",
    model: "hera",
    avatar: "/avatars/hera.png",
    audio: "/audio/hera.mp3",
  },
  {
    id: "minerva",
    firstName: "Minerva",
    lastName: "Sterling",
    gender: "female",
    model: "minerva",
    avatar: "/avatars/minerva.png",
    audio: "/audio/minerva.mp3",
  },

  // FRIENDLY & SOFT
  {
    id: "sarah",
    firstName: "Sarah",
    lastName: "Miller",
    gender: "female",
    model: "luna",
    avatar: "/avatars/sarah.png",
    audio: "/audio/sarah.mp3",
  },
  {
    id: "david",
    firstName: "David",
    lastName: "Wilson",
    gender: "male",
    model: "apollo",
    avatar: "/avatars/david.png",
    audio: "/audio/david.mp3",
  },
  {
    id: "lily",
    firstName: "Lily",
    lastName: "Bloom",
    gender: "female",
    model: "iris",
    avatar: "/avatars/lily.png",
    audio: "/audio/lily.mp3",
  },
  {
    id: "aurora",
    firstName: "Aurora",
    lastName: "Skye",
    gender: "female",
    model: "aurora",
    avatar: "/avatars/aurora.png",
    audio: "/audio/aurora.mp3",
  },
  {
    id: "cora",
    firstName: "Cora",
    lastName: "Hart",
    gender: "female",
    model: "cora",
    avatar: "/avatars/cora.png",
    audio: "/audio/cora.mp3",
  },

  // DEEP & MASCULINE
  {
    id: "marcus",
    firstName: "Marcus",
    lastName: "Stone",
    gender: "male",
    model: "orion",
    avatar: "/avatars/marcus.png",
    audio: "/audio/marcus.mp3",
  },
  {
    id: "james",
    firstName: "James",
    lastName: "Vance",
    gender: "male",
    model: "atlas",
    avatar: "/avatars/james.png",
    audio: "/audio/james.mp3",
  },
  {
    id: "leo",
    firstName: "Leo",
    lastName: "Knight",
    gender: "male",
    model: "mars",
    avatar: "/avatars/leo.png",
    audio: "/audio/leo.mp3",
  },
  {
    id: "noah",
    firstName: "Noah",
    lastName: "Grey",
    gender: "male",
    model: "neptune",
    avatar: "/avatars/noah.png",
    audio: "/audio/noah.mp3",
  },
  {
    id: "pluto",
    firstName: "Pluto",
    lastName: "Blackwood",
    gender: "male",
    model: "pluto",
    avatar: "/avatars/pluto.png",
    audio: "/audio/pluto.mp3",
  },
  {
    id: "saturn",
    firstName: "Saturn",
    lastName: "Elder",
    gender: "male",
    model: "saturn",
    avatar: "/avatars/saturn.png",
    audio: "/audio/saturn.mp3",
  },

  // ELEGANT & CLASSICAL
  {
    id: "elena",
    firstName: "Elena",
    lastName: "Rossi",
    gender: "female",
    model: "callista",
    avatar: "/avatars/elena.png",
    audio: "/audio/elena.mp3",
  },
  {
    id: "emma",
    firstName: "Emma",
    lastName: "Beaumont",
    gender: "female",
    model: "cordelia",
    avatar: "/avatars/emma.png",
    audio: "/audio/emma.mp3",
  },
  {
    id: "clara",
    firstName: "Clara",
    lastName: "Schumann",
    gender: "female",
    model: "ophelia",
    avatar: "/avatars/clara.png",
    audio: "/audio/clara.mp3",
  },
  {
    id: "helena",
    firstName: "Helena",
    lastName: "Troy",
    gender: "female",
    model: "helena",
    avatar: "/avatars/helena.png",
    audio: "/audio/helena.mp3",
  },

  // ADDITIONAL FEMALE VOICES
  {
    id: "amara",
    firstName: "Amara",
    lastName: "Sen",
    gender: "female",
    model: "amalthea",
    avatar: "/avatars/amara.png",
    audio: "/audio/amara.mp3",
  },
  {
    id: "andrea",
    firstName: "Andrea",
    lastName: "Santos",
    gender: "female",
    model: "andromeda",
    avatar: "/avatars/andrea.png",
    audio: "/audio/andrea.mp3",
  },
  {
    id: "astrid",
    firstName: "Astrid",
    lastName: "Solberg",
    gender: "female",
    model: "asteria",
    avatar: "/avatars/astrid.png",
    audio: "/audio/astrid.mp3",
  },
  {
    id: "delilah",
    firstName: "Delilah",
    lastName: "Del Ray",
    gender: "female",
    model: "delia",
    avatar: "/avatars/delilah.png",
    audio: "/audio/delilah.mp3",
  },
  {
    id: "electra",
    firstName: "Electra",
    lastName: "Sparks",
    gender: "female",
    model: "electra",
    avatar: "/avatars/electra.png",
    audio: "/audio/electra.mp3",
  },
  {
    id: "harmony",
    firstName: "Harmony",
    lastName: "Melendez",
    gender: "female",
    model: "harmonia",
    avatar: "/avatars/harmony.png",
    audio: "/audio/harmony.mp3",
  },
  {
    id: "juno",
    firstName: "Juno",
    lastName: "Temple",
    gender: "female",
    model: "juno",
    avatar: "/avatars/juno.png",
    audio: "/audio/juno.mp3",
  },
  {
    id: "pandora",
    firstName: "Pandora",
    lastName: "Hope",
    gender: "female",
    model: "pandora",
    avatar: "/avatars/pandora.png",
    audio: "/audio/pandora.mp3",
  },
  {
    id: "phoebe",
    firstName: "Phoebe",
    lastName: "Moon",
    gender: "female",
    model: "phoebe",
    avatar: "/avatars/phoebe.png",
    audio: "/audio/phoebe.mp3",
  },
  {
    id: "thalia",
    firstName: "Thalia",
    lastName: "Muses",
    gender: "female",
    model: "thalia",
    avatar: "/avatars/thalia.png",
    audio: "/audio/thalia.mp3",
  },
  {
    id: "thea",
    firstName: "Thea",
    lastName: "Helias",
    gender: "female",
    model: "theia",
    avatar: "/avatars/thea.png",
    audio: "/audio/thea.mp3",
  },
  {
    id: "vesta",
    firstName: "Vesta",
    lastName: "Hearth",
    gender: "female",
    model: "vesta",
    avatar: "/avatars/vesta.png",
    audio: "/audio/vesta.mp3",
  },

  // ADDITIONAL MALE VOICES
  {
    id: "arthur",
    firstName: "Arthur",
    lastName: "Pendragon",
    gender: "male",
    model: "aries",
    avatar: "/avatars/arthur.png",
    audio: "/audio/arthur.mp3",
  },
  {
    id: "arcas",
    firstName: "Arcas",
    lastName: "Callisto",
    gender: "male",
    model: "arcas",
    avatar: "/avatars/arcas.png",
    audio: "/audio/arcas.mp3",
  },
  {
    id: "draco",
    firstName: "Draco",
    lastName: "Stern",
    gender: "male",
    model: "draco",
    avatar: "/avatars/draco.png",
    audio: "/audio/draco.mp3",
  },
  {
    id: "hermes",
    firstName: "Hermes",
    lastName: "Swift",
    gender: "male",
    model: "hermes",
    avatar: "/avatars/hermes.png",
    audio: "/audio/hermes.mp3",
  },
  {
    id: "harold",
    firstName: "Harold",
    lastName: "Bright",
    gender: "male",
    model: "hyperion",
    avatar: "/avatars/harold.png",
    audio: "/audio/harold.mp3",
  },
  {
    id: "janus",
    firstName: "Janus",
    lastName: "Bifrost",
    gender: "male",
    model: "janus",
    avatar: "/avatars/janus.png",
    audio: "/audio/janus.mp3",
  },
  {
    id: "oliver",
    firstName: "Oliver",
    lastName: "Queen",
    gender: "male",
    model: "odysseus",
    avatar: "/avatars/oliver.png",
    audio: "/audio/oliver.mp3",
  },
  {
    id: "orpheus",
    firstName: "Orpheus",
    lastName: "Harp",
    gender: "male",
    model: "orpheus",
    avatar: "/avatars/orpheus.png",
    audio: "/audio/orpheus.mp3",
  },
]

export function getCharacter(id: string): Character | undefined {
  return CHARACTERS.find((c) => c.id === id)
}
